### ISSUE TITLE
Sonic GLVL needs a direct tool download.

### ISSUE THREAD

**Issue by glitchgod0** [HedgeDocs/HedgeDocs.github.io#40]
As of 21/05/23 the GLVL page only links to the GitHub which lacks pre-compiled builds. This makes downloading GLVL 0.9 quite cumbersome.

**Comment by blueskythlikesclouds** [comment]
The precompiled builds are in the [bin](https://github.com/DarioSamo/libgens-sonicglvl/tree/master/bin) folder.

**Comment by glitchgod0** [comment]
I would recommend changing the link to go to the bin folder instead of the main repo page or adding information on where the executables are.

**Comment by PTKay** [comment]
You need to download the entire repository for GLvl to work. The bin folder contains the executables, but the other folder (except for the "src" folder) are still relevant for the tool.

So to sum up, the link should remain to the repository itself and not to the bin folder. As "bin" is already common practice as an executable folder, I don't think there's a need to make any additional remarks for this.

With all of this in mind, I'm closing this issue, but thanks for reporting :)
