### ISSUE TITLE
HedgeEdit broke in some windows update, update the compiled apps to use fixed version

### ISSUE THREAD

**Issue by KnolaWT** [HedgeDocs/HedgeDocs.github.io#53]
Theres a slightly newer version which has texture tiling options and also fixes the issue
[HedgeEdit.zip](https://github.com/HedgeDocs/HedgeDocs.github.io/files/12873762/HedgeEdit.zip)
Can you fix the compiled apps to have this newer version? Thanks in advance

**Comment by PTKay** [comment]
Thanks for the info! We updated HedgeEdit the same day this issue was posted, but forgot to update you here. This has been dealt with :)
